In [3]:
import pandas as pd
import numpy as np
import joblib

In [9]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
import matplotlib.pyplot as plt

In [13]:
df = pd.read_csv("irrigation_prediction.csv")
df.head()

,Soil_Type,Soil_pH,Soil_Moisture,Organic_Carbon,Electrical_Conductivity,Temperature_C,Humidity,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Crop_Type,Crop_Growth_Stage,Season,Irrigation_Type,Water_Source,Field_Area_hectare,Mulching_Used,Previous_Irrigation_mm,Region,Irrigation_Need
0,Clay,6.14,36.48,0.42,2.17,21.90,31.19,1167.70,4.01,1.97,Wheat,Vegetative,Rabi,Rainfed,Reservoir,4.73,Yes,1.98,South,Low
1,Silt,6.41,50.56,0.38,0.23,36.50,26.01,831.28,10.72,16.82,Maize,Flowering,Zaid,Canal,Groundwater,12.22,Yes,33.56,Central,Medium
2,Sandy,7.71,40.07,1.09,2.18,41.83,76.41,1844.45,7.75,19.03,Cotton,Harvest,Rabi,Drip,Reservoir,5.52,Yes,34.62,South,Low
3,Clay,5.96,12.75,1.56,0.40,37.22,43.32,306.26,8.90,11.44,Wheat,Sowing,Kharif,Canal,Reservoir,1.43,Yes,84.03,North,Medium
4,Clay,7.76,18.58,0.95,2.52,22.38,86.44,1875.63,10.39,11.26,Cotton,Sowing,Zaid,Canal,River,2.52,No,60.86,South,Medium

In [15]:
df = df[["Temperature_C", "Humidity", "Soil_Moisture", "Rainfall_mm", "Sunlight_Hours", "Wind_Speed_kmh", "Soil_pH", "Irrigation_Need",]]
df.head()

,Temperature_C,Humidity,Soil_Moisture,Rainfall_mm,Sunlight_Hours,Wind_Speed_kmh,Soil_pH,Irrigation_Need
0,21.90,31.19,36.48,1167.70,4.01,1.97,6.14,Low
1,36.50,26.01,50.56,831.28,10.72,16.82,6.41,Medium
2,41.83,76.41,40.07,1844.45,7.75,19.03,7.71,Low
3,37.22,43.32,12.75,306.26,8.90,11.44,5.96,Medium
4,22.38,86.44,18.58,1875.63,10.39,11.26,7.76,Medium

In [17]:
print(df.info())
print(df.isnull().sum())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Temperature_C    10000 non-null  float64
 1   Humidity         10000 non-null  float64
 2   Soil_Moisture    10000 non-null  float64
 3   Rainfall_mm      10000 non-null  float64
 4   Sunlight_Hours   10000 non-null  float64
 5   Wind_Speed_kmh   10000 non-null  float64
 6   Soil_pH          10000 non-null  float64
 7   Irrigation_Need  10000 non-null  object
dtypes: float64(7), object(1)
memory usage: 625.1+ KB
None
Temperature_C      0
Humidity           0
Soil_Moisture      0
Rainfall_mm        0
Sunlight_Hours     0
Wind_Speed_kmh     0
Soil_pH            0
Irrigation_Need    0
dtype: int64

In [21]:
X = df.drop("Irrigation_Need", axis=1)
y = df["Irrigation_Need"]

In [23]:
X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.2)

In [25]:
model = RandomForestClassifier(n_estimators=100)
model.fit(X_train,y_train)

RandomForestClassifier()

In [31]:
result = model.predict(X_test)
print("Accuracy:", accuracy_score(y_test, result))
print("\nClassification Report:\n", classification_report(y_test, result))

Accuracy: 0.7405

Classification Report:
               precision    recall  f1-score   support

        High       0.48      0.25      0.33        59
         Low       0.80      0.83      0.81      1211
      Medium       0.65      0.64      0.64       730

    accuracy                           0.74      2000
   macro avg       0.64      0.57      0.60      2000
weighted avg       0.74      0.74      0.74      2000

In [33]:
joblib.dump(model, "irrigation_model.pkl")

['irrigation_model.pkl']

In [51]:
sample_input = [[
    40,   # Temperature
    50,   # Humidity
    40,   # Soil Moisture
    5,    # Rainfall
    2,    # Sunlight
    10,   # Wind Speed
    6.5   # Soil pH
]]

prediction = model.predict(sample_input)[0]
print("Prediction:", prediction)

Prediction: Medium

C:\Users\bahug\anaconda3\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(